// One icon system for the whole dashboard (lucide, single stroke weight) so no
// screen ever falls back to emoji, and every icon has a semantic name instead of
// a component name. Public-site icons live in the components.
import {
  Activity,
  ArrowLeftRight,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  ArrowUpLeft,
  BadgePercent,
  Bell,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  ClipboardList,
  Clock,
  CalendarCheck,
  CloudUpload,
  Cog,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gauge,
  Globe,
  History,
  Hash,
  Lightbulb,
  LogIn,
  MapPin,
  MessageCircle,
  MoreHorizontal,
  Store,
  Timer,
  TrendingUp,
  Undo2,
  HelpCircle,
  Image as ImageIcon,
  ImageOff,
  Images,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  ListChecks,
  ListOrdered,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  MessageSquareQuote,
  Moon,
  Package,
  PackageSearch,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Save,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Tags,
  Trash2,
  Truck,
  Type,
  UserCircle2,
  UserCog,
  UserPlus,
  Users,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export type IconProps = {
  size?: number;
  className?: string;
  strokeWidth?: number;
};

const wrap = (Icon: LucideIcon) =>
  function IconComponent({
    size = 18,
    className,
    strokeWidth = 1.75,
  }: IconProps) {
    return (
      <Icon
        size={size}
        className={className}
        strokeWidth={strokeWidth}
        aria-hidden="true"
      />
    );
  };

export const Icons = {
  activity: wrap(Activity),
  arrowSwap: wrap(ArrowLeftRight),
  alert: wrap(AlertTriangle),
  arrowDown: wrap(ArrowDown),
  arrowUp: wrap(ArrowUp),
  arrowUpLeft: wrap(ArrowUpLeft),
  badgePercent: wrap(BadgePercent),
  bell: wrap(Bell),
  boxes: wrap(Boxes),
  brand: wrap(Building2),
  calendar: wrap(CalendarDays),
  calendarCheck: wrap(CalendarCheck),
  calendarClock: wrap(CalendarClock),
  calendarRange: wrap(CalendarRange),
  check: wrap(Check),
  checkAll: wrap(CheckCheck),
  checkCircle: wrap(CheckCircle2),
  chevronDown: wrap(ChevronDown),
  chevronLeft: wrap(ChevronLeft),
  chevronRight: wrap(ChevronRight),
  chevronUp: wrap(ChevronUp),
  clipboard: wrap(ClipboardList),
  clock: wrap(Clock),
  close: wrap(X),
  closeCircle: wrap(XCircle),
  collapse: wrap(PanelLeftClose),
  copy: wrap(Copy),
  download: wrap(Download),
  external: wrap(ExternalLink),
  dashboard: wrap(LayoutDashboard),
  error: wrap(XCircle),
  events: wrap(Megaphone),
  expand: wrap(PanelLeftOpen),
  eye: wrap(Eye),
  eyeOff: wrap(EyeOff),
  file: wrap(FileText),
  filter: wrap(Filter),
  gauge: wrap(Gauge),
  globe: wrap(Globe),
  history: wrap(History),
  idea: wrap(Lightbulb),
  login: wrap(LogIn),
  mapPin: wrap(MapPin),
  megaphone: wrap(Megaphone),
  message: wrap(MessageCircle),
  more: wrap(MoreHorizontal),
  grid: wrap(LayoutGrid),
  hash: wrap(Hash),
  help: wrap(HelpCircle),
  helpCircle: wrap(CircleHelp),
  image: wrap(ImageIcon),
  imageOff: wrap(ImageOff),
  images: wrap(Images),
  inbox: wrap(Inbox),
  info: wrap(Info),
  key: wrap(KeyRound),
  link: wrap(Link2),
  list: wrap(ListChecks),
  listOrdered: wrap(ListOrdered),
  loader: wrap(Loader2),
  lock: wrap(Lock),
  logout: wrap(LogOut),
  mail: wrap(Mail),
  menu: wrap(Menu),
  moon: wrap(Moon),
  offline: wrap(WifiOff),
  online: wrap(Wifi),
  package: wrap(Package),
  packageSearch: wrap(PackageSearch),
  palette: wrap(Palette),
  pencil: wrap(Pencil),
  phone: wrap(Phone),
  plus: wrap(Plus),
  quote: wrap(MessageSquareQuote),
  refresh: wrap(RefreshCw),
  railClose: wrap(PanelLeftClose),
  railOpen: wrap(PanelLeftOpen),
  save: wrap(Save),
  search: wrap(Search),
  settings: wrap(Cog),
  shield: wrap(ShieldCheck),
  sliders: wrap(SlidersHorizontal),
  sparkles: wrap(Sparkles),
  star: wrap(Star),
  store: wrap(Store),
  timer: wrap(Timer),
  trend: wrap(TrendingUp),
  undo: wrap(Undo2),
  sun: wrap(Sun),
  tags: wrap(Tags),
  text: wrap(Type),
  trash: wrap(Trash2),
  truck: wrap(Truck),
  upload: wrap(CloudUpload),
  user: wrap(UserCircle2),
  userCog: wrap(UserCog),
  userPlus: wrap(UserPlus),
  users: wrap(Users),
};

export type IconName = keyof typeof Icons;
