// One icon system for the whole dashboard (lucide, single stroke weight) so no
// screen ever falls back to emoji. Public-site icons live in the components.
import {
  Activity,
  AlertTriangle,
  ArrowUpLeft,
  BadgePercent,
  Bell,
  Building2,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CloudUpload,
  Cog,
  Copy,
  Eye,
  EyeOff,
  FileText,
  Gauge,
  HelpCircle,
  Image as ImageIcon,
  ImageOff,
  Info,
  KeyRound,
  LayoutDashboard,
  Link2,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Megaphone,
  Moon,
  Package,
  PackageSearch,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  Save,
  Search,
  ShieldCheck,
  Sparkles,
  Sun,
  Trash2,
  Truck,
  UserCircle2,
  UserCog,
  UserPlus,
  Users,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export type IconProps = { size?: number; className?: string; strokeWidth?: number };

const wrap = (Icon: LucideIcon) =>
  function IconComponent({ size = 18, className, strokeWidth = 1.75 }: IconProps) {
    return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
  };

export const Icons = {
  activity: wrap(Activity),
  alert: wrap(AlertTriangle),
  arrowUpLeft: wrap(ArrowUpLeft),
  badgePercent: wrap(BadgePercent),
  bell: wrap(Bell),
  brand: wrap(Building2),
  calendar: wrap(CalendarDays),
  calendarRange: wrap(CalendarRange),
  check: wrap(Check),
  checkCircle: wrap(CheckCircle2),
  chevronDown: wrap(ChevronDown),
  chevronLeft: wrap(ChevronLeft),
  chevronRight: wrap(ChevronRight),
  clock: wrap(Clock),
  close: wrap(X),
  closeCircle: wrap(XCircle),
  copy: wrap(Copy),
  dashboard: wrap(LayoutDashboard),
  error: wrap(XCircle),
  events: wrap(Megaphone),
  eye: wrap(Eye),
  eyeOff: wrap(EyeOff),
  file: wrap(FileText),
  gauge: wrap(Gauge),
  help: wrap(HelpCircle),
  image: wrap(ImageIcon),
  imageOff: wrap(ImageOff),
  info: wrap(Info),
  key: wrap(KeyRound),
  link: wrap(Link2),
  list: wrap(ListChecks),
  loader: wrap(Loader2),
  lock: wrap(Lock),
  logout: wrap(LogOut),
  mail: wrap(Mail),
  menu: wrap(Menu),
  moon: wrap(Moon),
  package: wrap(Package),
  packageSearch: wrap(PackageSearch),
  palette: wrap(Palette),
  pencil: wrap(Pencil),
  plus: wrap(Plus),
  refresh: wrap(RefreshCw),
  save: wrap(Save),
  search: wrap(Search),
  settings: wrap(Cog),
  shield: wrap(ShieldCheck),
  sparkles: wrap(Sparkles),
  sun: wrap(Sun),
  trash: wrap(Trash2),
  truck: wrap(Truck),
  upload: wrap(CloudUpload),
  user: wrap(UserCircle2),
  userCog: wrap(UserCog),
  userPlus: wrap(UserPlus),
  users: wrap(Users),
  online: wrap(Wifi),
  offline: wrap(WifiOff),
};
